AllCops:
  Exclude:
    - 'spec/examples/**/*'

Style/BracesAroundHashParameters:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/SignalException:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false
