development:
  database:
    name: tasks-example_development
    host: 127.0.0.1
    port: 27017

test:
  database:
    name: tasks-example_test
    host: 127.0.0.1
    port: 27017

production:
  database:
    name: tasks-example
    host: 127.0.0.1
    port: 27017
