development:
  database:
    name: todo_development
    host: 127.0.0.1
    port: 27017

test:
  database:
    name: todo_test
    host: 127.0.0.1
    port: 27017

production:
  database:
    name: todo
    host: 127.0.0.1
    port: 27017
