development:
  database:
    name: couch-lock_development
    host: 127.0.0.1
    port: 27017

test:
  database:
    name: couch-lock_test
    host: 127.0.0.1
    port: 27017

production:
  database:
    name: couch-lock
    host: 127.0.0.1
    port: 27017
